### ISSUE TITLE
✋ More friendly title

### ISSUE THREAD

**Issue by miyaoka** [soussune/soussune.github.io#8]
# 課題
- タイトルが英字だけだと日本人の9割は目に入らず読み飛ばしてしまう（印象）
- ポッドキャストということがタイトルに入ってない

### google検索結果
<img width="654" alt="2017-08-01 3 16 22" src="https://user-images.githubusercontent.com/1443118/28791582-ebb4629a-7667-11e7-8912-d3039e1e33cd.png">

### hatena bookmark
<img width="657" alt="2017-08-01 3 18 34" src="https://user-images.githubusercontent.com/1443118/28791673-2547a102-7668-11e7-92ce-3b61e835a8a9.png">

# 対策
「soussune - エンジニアわいわいポッドキャスト」
のような感じでめちゃ分かりやすい日本語をつけたい

**Comment by trkw** [comment]
そうっすね。タイトルの区切りは`-`で表現したいですね。

```
soussune - そうっすねはエンジニアがわいわいしてるポッドキャスト
```

冗長かもしれないけど、そうっすねという日本語もいれたい気がする。

↓

`|`でもエスケープすればいいか
